---
all:
  children:
    monitoring_servers:
      hosts:
        monitor-01:
    monitoring_clients:
      hosts:
        client-01:
    monitoring:
      children:
        monitoring_servers:
        monitoring_clients: