---
- name: Tags for the monitoring server
  hosts: monitoring_servers
  gather_facts: true
  become: true
  become_method: sudo
  roles:
    - {role: 'prometheus_server', tags: ['all']}

- name: Tags for the monitoring clienhts
  hosts: monitoring_clients
  gather_facts: true
  become: true
  become_method: sudo
  roles:
    - {role: 'prometheus_client', tags: ['all']}

- name: Tags for the grafana server
  hosts: monitoring_servers
  gather_facts: true
  become: true
  become_method: sudo
  roles:
    - {role: 'grafana_server', tags: ['all']}