---
- name: Update monitoring machines
  hosts: monitoring
  gather_facts: true
  become: true
  become_method: sudo
  roles:
    - {role: 'update', tags: ['update']}

- name: Monitoring Servers setup
  hosts: monitoring_servers
  gather_facts: true
  become: true
  become_method: sudo
  roles:
    - {role: 'prometheus_server', tags: ['prometheus']}
    - {role: 'grafana_server', tags: ['grafana']}


- name: Monitoring Clients setup
  hosts: monitoring_clients
  gather_facts: true
  become: true
  become_method: sudo
  roles:
    - {role: 'prometheus_client', tags: ['node_exporter']}
    - {role: 'docker', tags: ['docker']}
    - {role: 'wordpress', tags: ['wordpress']}